name: Cron France Travail

# Lancer toutes les heures + possibilité de déclenchement manuel
on:
  schedule:
    - cron: '0 * * * *' # toutes les heures
  workflow_dispatch:

jobs:
  fetch-offres:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run France Travail cron
        run: npm start
        env:
          FT_CLIENT_ID: ${{ secrets.FT_CLIENT_ID }}
          FT_CLIENT_SECRET: ${{ secrets.FT_CLIENT_SECRET }}

      - name: Upload offres JSON
        uses: actions/upload-artifact@v4
        with:
          name: ./data/ft-offres.json
          path: ./data/ft-offres.json
