name: Cron France Travail

on:
  schedule:
    - cron: '0 * * * *' # toutes les heures
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run cron script
        run: npm start
        env:
          FT_CLIENT_ID: ${{ secrets.FT_CLIENT_ID }}
          FT_CLIENT_SECRET: ${{ secrets.FT_CLIENT_SECRET }}
